#!/usr/bin/env python3
#
# CS3700, Fall 2021
# TCP Project Starter Code


import datetime
import json
import sys
import socket

from base64 import b64decode


def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " 3700recv: " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = int(sys.argv[1])

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

lastSequence = "-1"
receivedPackets = set()

# Now listen for packets
while True:
  try:
    result = sock.recvfrom(MSG_SIZE)
  except socket.timeout:
    #didn't receive so ask them to resent
    print("right before try to send a -1 ack")
    msg = json.dumps({"ack": "-1"})
    log("ABOUT TO SEND " + msg)
    sent = sock.sendto(msg.encode(), addr)
    log("[sent] " + str(sent))


  # If nothing is ready, we hit the timeout
  if result:
(data, addr) = result

    try:
      decoded = json.loads(data.decode())

      # If the EOF flag is set, exit
      if (decoded['eof']):
        log("[completed]")
        sys.exit(0)

      # If there is data, we accept it and print it out
      if (decoded['data']): #@@@@@@@@@and !(decoded['sequence'] in receivedPackets)):
        data = b64decode(decoded['data'].encode())
        # If we receive data, we assume it's in-order
        # You will need to do much more here@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        log("[recv data] " + str(decoded['sequence']) + " (" + str(len(data)) + ") ACCEPTED (in-order)")
        lastSequence = str(decoded['sequence'])
        #@@@@@@@@added below this------------------------------
        if (decoded['sequence'] not in receivedPackets):
          sys.stdout.buffer.write(data)
        #print("onlyyyyyy write here once")
        receivedPackets.add(decoded['sequence'])
        #print("recieved packet length : " + str(len(receivedPackets)))

      # Send back an ack to the sender
      #@@@@@@@@@if (!(decoded['sequence'] in receivedPackets)):
        msg = json.dumps({"ack": decoded['sequence'] + len(data)})
        log("ABOUT TO SEND " + msg)
        sent = sock.sendto(msg.encode(), addr)
        log("[sent] " + str(sent))
        if sent < len(msg):
          log("[error] unable to fully send packet")

    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    print("IT TIMED OUT")
    log("[error] timeout")
    msg = json.dumps({"ack": str(lastSequence)})
    log("ABOUT TO SEND " + msg)
    sent = sock.sendto(msg.encode(), addr)
    log("[sent] " + str(sent))
    sys.exit(-1)
