#!/usr/bin/python3
#
# CS3700, Fall 2021
# TCP Project Starter Code
#

import datetime
import json
import sys
import socket
import time

from base64 import b64encode

# Keep track of sent and acked packets with their sequence number as key
# SentPackets has (packet, time + rtt, time) as its value
sentPackets = {}
ackPackets = set()

WINDOW = 1

MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 30
SEQUENCE = 0

RTTIME = 0.5

# all packets have been sent
FINISHED = False

# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

time.sleep(.5)

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(1)


def log(string):
    sys.stderr.write(datetime.datetime.now().strftime(
        "%H:%M:%S.%f") + " 3700send: " + string + "\n")


def send_next_packet():
    global SEQUENCE
    global FINISHED
    data = sys.stdin.buffer.read(DATA_SIZE)
    # Data to send
    if (len(data) > 0):
        
        msg = json.dumps({"sequence": SEQUENCE, "data": b64encode(
            data).decode(), "ack": False, "eof": False})
        SEQUENCE += len(data)
        sendTime = time.time()
        sentPackets[SEQUENCE] = (msg, sendTime + (2*RTTIME), sendTime)
        if sock.sendto(msg.encode(), dest) < len(msg):
            log("[error] unable to fully send packet")
        else:
            log("[send data] " + str(SEQUENCE) + " (" + str(len(data)) + ")")
        return True
    
    else:
        FINISHED = True
        return False

# Resends the packet with the given sequence number
def resend(seq):
    packet = sentPackets[seq][0]
    sendTime = time.time()
    sentPackets[seq] = (packet, sendTime + (2*RTTIME), sendTime)
    if sock.sendto(packet.encode(), dest) < len(packet):
        log("[error] unable to fully send packet")
    else:
        log("[send data] " + str(SEQUENCE) +
            " (" + str(len(packet)) + ")")
    return True


# Send first packet
send_next_packet()

# Now read in data, send packets
while True:
    log("ABOUT TO SLEEP")
    try:
        result = sock.recvfrom(MSG_SIZE)
    except socket.timeout:
        result = None
    lastTime = time.time()
    if result:
        (data, addr) = result
        try:
            lastTime = time.time()
            decoded = json.loads(data.decode())
            log("[recv pkt] " + str(decoded))
            log("[recv ack] " + str(decoded['ack']))

            # If new ack number, then modify RTTIME and congestion window
            if decoded['ack'] not in ackPackets:
                RTTIME = (0.875 * RTTIME) + \
                    (1 - 0.875) * (lastTime -
                                   sentPackets[decoded['ack']][2])
                print("RTT: ", RTTIME)
                WINDOW += 1
                ackPackets.add(decoded['ack'])
            
            
            # Send packets in respect to the congestion window 
            while len(sentPackets) - len(ackPackets) < WINDOW:
                if (not send_next_packet()):
                    break
            # If all packets are sent, we break the while loop
            if FINISHED and len(ackPackets) == len(set(sentPackets)):
                break

        except (ValueError, KeyError, TypeError):
            log("[recv corrupt packet]")

    # Retransmit dropped packet
    newTime = time.time()
    if (newTime-lastTime)*1000 < TIMEOUT:
        for seq, packet in sentPackets.items():
            if seq not in ackPackets and newTime > packet[1]:
                log("packet " + str(newTime -
                    packet[1]))
                resend(seq)
                WINDOW = 1
    else:
        log("[error] timeout")
        sys.exit(-1)
        
# print("END")
# Sending 10 times to ensure the EOF is not dropped...
for _ in range(10):
    sock.sendto(json.dumps({"eof": True, "data": "",
                            "sequence": SEQUENCE, "ack": False}).encode(), dest)
sys.exit(0)
